### PR TITLE
[WFCC-33] Processing of wildfly.config.url does not check for empty s…

### PR DESCRIPTION
**Pull request by moulalis**
Issue : https://issues.redhat.com/browse/WFCC-33

### CODE REVIEW

**Review by ropalka — APPROVED** [review]
LGTM

**Comment by moulalis** [comment]
Thanks @ropalka

**Comment by rachmatowicz** [comment]
If the system property is not null, then the system, property has been set, but to an incorrect value. No warning of this?

**Comment by ropalka** [comment]
In such case ClientConfiguration#readConfiguration() method will fail @rachmatowicz . It behaves this way since the beginning.

**Pull request merged**
